// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvaojquxsqzpdjguzfoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2YW9qcXV4c3F6cGRqZ3V6Zm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Mzg5MTUsImV4cCI6MjA2NTIxNDkxNX0.zfN0wpDZJKIxkkSfSDAcSQIdwF32TcbCKkej73o53-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);